import express from 'express';
import Task from '../models/task.model.js';

const router = express.Router();

// Create a new task
router.post('/add', async (req, res) => {
    try {
        const { pro_id, title, description, category_id, location_id, price } = req.body;

        // Assuming task_id is auto-generated by MongoDB
        const newTask = new Task({
            pro_id,
            title,
            description,
            category_id,
            location_id,
            price
        });

        const savedTask = await newTask.save();
        res.status(201).json({ message: 'Task added successfully', task: savedTask });
    } catch (error) {
        console.error('Error adding task:', error.message);
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

// Get all tasks
router.get('/all', async (req, res) => {
    try {
        const tasks = await Task.find().populate('pro_id category_id location_id');
        res.status(200).json(tasks);
    } catch (error) {
        console.error('Error fetching tasks:', error.message);
        res.status(500).json({ error: 'Internal Server Error' });
    }
});

export default router;
